name: Build and Push Docker Image

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  IMAGE_NAME: online-cv

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CK98_REGISTRY_PASSWORD }}" | docker login ${{ vars.CK98_REGISTRY_URL }} -u '${{ vars.CK98_REGISTRY_USERNAME }}' --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.CK98_REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7} .
          docker tag  ${{ vars.CK98_REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7} ${{ vars.CK98_REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ vars.CK98_REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}
          docker push ${{ vars.CK98_REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Notify Portainer
        run: |
          curl -X POST ${{ vars.PORTAINER_WEBHOOK_URL }}
